#!/usr/bin/env bash
set -Eeuo pipefail

subjects_file=/var/run/lice-bootstrap/subjects.env
if [[ ! -f "$subjects_file" ]]; then
  echo "Arquivo de subjects do Keycloak nao encontrado." >&2
  exit 1
fi

# The file is generated by seed-demo-users.sh and contains only validated
# Keycloak IDs. Usernames are intentionally unavailable to this process.
set -a
# shellcheck disable=SC1090
source "$subjects_file"
set +a

for name in LICE_OPERATOR_SUBJECT LICE_VIEWER_SUBJECT; do
  if [[ ! "${!name:-}" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]]; then
    echo "Subject obrigatorio ausente ou invalido: ${name}" >&2
    exit 1
  fi
done

exec /out/lice-admin bootstrap-demo \
  --operator-subject "$LICE_OPERATOR_SUBJECT" \
  --viewer-subject "$LICE_VIEWER_SUBJECT"
